micronaut:
  application:
    name: Product Category
  server:
    port: 8086

datasources:
  default:
    url: 'jdbc:h2:mem:productCategoryDb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE'
    username: 'sa'
    password: ''
    driverClassName: 'org.h2.Driver'
jpa:
  default:
    packages-to-scan:
      - 'com.ms.category.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true
  endpoints:
    flyway:
      enabled: true
      sensitive: false